apiVersion: apps/v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: task-board
      labels:
        app: task-board
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: task-board
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
      template:
        metadata:
          labels:
            app: task-board
        spec:
          containers:
          - name: task-board
            image: task-board:v1.0.0
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 30000
              - containerPort: 30001
            command: ["bash"]
            args: ["start.bash"]
            volumeMounts:
              - name: cfg
                mountPath: /app/cfg
              - name: json-server-pvc
                mountPath: /app/data
            env:
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            resources:
              requests:
                memory: "512Mi"
          volumes:
            - name: cfg
              configMap:
                name: task-board-configmap
            - name: json-server-pvc
              persistentVolumeClaim:
                claimName: json-server-pvc
  ################################################################
  - apiVersion: v1
    kind: Service
    metadata:
      name: task-board
    spec:
      type: NodePort
      selector:
        app: task-board
      ports:
        - name: frontend-server
          nodePort: 30901
          port: 30000
          targetPort: 30000
        - name: json-server
          nodePort: 30902
          port: 30001
          targetPort: 30001
    ################################################################
